const API='/api';
let token=localStorage.getItem('leadflow_token')||'';
let me=null,users=[],stages=[],tags=[],leads=[],notifications=[];
let theme=localStorage.getItem('leadflow_theme')||'light';
let state={page:'pipeline',q:'',view:'kanban',stage:'all',user:'all',tag:'all',selected:null,modal:null,selectedIds:new Set(),activity:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const user=id=>users.find(x=>x.id===id), stage=id=>stages.find(x=>x.id===id), tag=id=>tags.find(x=>x.id===id);
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(token)headers.Authorization='Bearer '+token;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{let r=await fetch(API+path,{...opt,headers,signal:controller.signal});let text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch(_){d={detail:text||'Server returned an invalid response'}}if(r.status===401){token='';localStorage.removeItem('leadflow_token');me=null;if(path!=='/auth/login')render();throw Error(path==='/auth/login'?(d.detail||'Invalid email or password'):'Your session expired. Please sign in again.')}if(!r.ok)throw Error(d.detail||'Request failed');return d}catch(err){if(err.name==='AbortError')throw Error('The CRM server did not respond within 12 seconds. Check the Render deployment.');throw err}finally{clearTimeout(timer)}}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}
function render(){document.documentElement.dataset.theme=theme;if(!me){document.getElementById('app').innerHTML=loginPage();return}document.getElementById('app').innerHTML=`<div class="app"><aside class="sidebar"><div class="brand"><img class="brand-logo" src="/destino-logo.svg" alt="Destino Travels"></div>${nav('pipeline','▦','Pipeline')}${nav('leads','☷','All Leads')}${nav('users','♙','Team')}${nav('settings','⚙','Settings')}<div class="userbox"><div class="avatar">${esc(me.avatar)}</div><div class="usertext"><b>${esc(me.name)}</b><small class="muted" style="display:block">${esc(me.role)} · ${esc(me.agentId||'')}</small></div><button class="btn iconbtn" title="Sign out" onclick="logout()">↪</button></div></aside><main class="workspace"><header class="topbar"><div class="global-search">⌕<input placeholder="Search name, phone, email or company" value="${esc(state.q)}" oninput="state.q=this.value;render()"></div><div class="top-actions"><button class="btn iconbtn" title="Notifications" onclick="showNotifications()">🔔 <span class="notif-count">${notifications.filter(n=>!n.read).length}</span></button><button class="btn iconbtn" title="Toggle theme" onclick="theme=theme==='light'?'dark':'light';localStorage.setItem('leadflow_theme',theme);render()">${theme==='light'?'☾':'☀'}</button><button class="btn" onclick="state.modal='import';render()">⇧ Import</button><button class="btn primary" onclick="state.modal='add';render()">＋ Add Lead</button></div></header>${page()}</main></div>${state.selected?drawer(state.selected):''}${state.modal==='add'?addModal():''}${state.modal==='import'?importModal():''}${state.modal==='agent'?agentModal():''}${state.modal==='editAgent'&&state.editUser?editAgentModal(user(state.editUser)):''}`;requestAnimationFrame(syncBoardScroll)}
function syncBoardScroll(){
  const top=document.getElementById('boardScrollTop'), board=document.getElementById('leadBoard'), inner=document.getElementById('boardScrollInner');
  if(!top||!board||!inner)return;
  inner.style.width=board.scrollWidth+'px';
  let syncing=false;
  top.onscroll=()=>{if(syncing)return;syncing=true;board.scrollLeft=top.scrollLeft;syncing=false};
  board.onscroll=()=>{if(syncing)return;syncing=true;top.scrollLeft=board.scrollLeft;syncing=false};
}
function loginPage(){return `<div class="login-shell"><div class="login-photo" aria-hidden="true"></div><div class="login-overlay"></div><div class="login-content"><form class="login-card" onsubmit="login(this,event)"><div class="brand login-brand"><img class="brand-logo" src="/destino-logo.svg" alt="Destino Travels"></div><div class="login-kicker">DESTINO TRAVELS</div><h1>Welcome back</h1><p class="login-subtitle">Sign in to your sales workspace and manage your travel leads.</p><div class="field"><label>Email</label><input name="email" type="email" placeholder="Enter your email" autocomplete="username" required></div><div class="field"><label>Password</label><input name="password" type="password" placeholder="Enter your password" autocomplete="current-password" required></div><button class="btn primary login-submit">Sign in</button><div class="login-footer">Secure access · Destino Lead Management System</div></form></div></div>`}
async function login(form,e){e.preventDefault();if(!form||form.tagName!=='FORM'){toast('Login form could not be read. Please refresh the page.');return}const email=form.elements.email?.value?.trim()||'';const password=form.elements.password?.value||'';if(!email||!password){toast('Enter your email and password.');return}const button=form.querySelector('button[type=submit],button');if(button){button.disabled=true;button.textContent='Signing in…'}try{const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});token=r.token;localStorage.setItem('leadflow_token',token);me=r.user;await loadData();render();toast('Welcome back')}catch(err){toast(err.message||'Login failed')}finally{if(button){button.disabled=false;button.textContent='Sign in'}}}
function nav(p,ico,label){return `<button class="nav ${state.page===p?'active':''}" onclick="go('${p}')"><span class="ico">${ico}</span><span>${label}</span></button>`}
function page(){if(state.page==='users')return usersPage();if(state.page==='settings')return settingsPage();return pipelinePage()}
function visible(){let q=state.q.toLowerCase();return leads.filter(l=>(!q||[l.name,l.phone,l.email,l.company,l.source].some(x=>String(x||'').toLowerCase().includes(q)))&&(state.stage==='all'||l.stageId===state.stage)&&(state.user==='all'||l.assignedUserId===state.user)&&(state.tag==='all'||l.tagIds.includes(state.tag)))}
function pipelinePage(){let f=visible(), converted=leads.filter(l=>stage(l.stageId)?.name.toLowerCase().includes('converted')).length;return `<section class="content"><div class="head"><div><h1>Pipeline</h1><p>Manage leads visually from first contact to conversion.</p></div><div class="actions"><button class="btn" onclick="state.modal='import';render()">⇧ Import</button><button class="btn" onclick="exportCSV()">⇩ Export</button></div></div><div class="kpis">${kpi('Total Leads',leads.length)}${stages.slice(0,4).map(s=>kpi(s.name,leads.filter(l=>l.stageId===s.id).length)).join('')}${kpi('Converted',converted)}${kpi('Conversion',leads.length?Math.round(converted/leads.length*100)+'%':'0%')}</div><div class="toolbar"><div class="filters"><select class="select" onchange="state.stage=this.value;render()"><option value="all">All stages</option>${stages.map(s=>`<option value="${s.id}" ${state.stage===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select><select class="select" onchange="state.user=this.value;render()"><option value="all">All owners</option>${users.map(u=>`<option value="${u.id}" ${state.user===u.id?'selected':''}>${esc(u.name)}</option>`).join('')}</select><select class="select" onchange="state.tag=this.value;render()"><option value="all">All tags</option>${tags.map(t=>`<option value="${t.id}" ${state.tag===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select><button class="btn" onclick="state.user=me.id;render()">Tagged to me</button></div><div class="seg"><button class="${state.view==='kanban'?'on':''}" onclick="state.view='kanban';render()">Kanban</button><button class="${state.view==='table'?'on':''}" onclick="state.view='table';render()">Table</button></div></div>${state.selectedIds.size?bulkbar():''}${state.view==='kanban'?kanban(f):table(f)}</section>`}
function kpi(a,b){return `<div class="kpi"><label>${esc(a)}</label><strong>${b}</strong></div>`}
function bulkbar(){return `<div class="bulkbar"><b>${state.selectedIds.size} selected</b><select class="select" onchange="bulkStage(this.value)"><option value="">Change stage…</option>${stages.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><select class="select" onchange="bulkAssign(this.value)"><option value="">Assign…</option>${users.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select><button class="btn" onclick="bulkTag()">+ Tag</button><button class="btn" onclick="state.selectedIds.clear();render()">Clear</button></div>`}
function kanban(f){return `<div class="board-scroll-top" id="boardScrollTop" aria-label="Horizontal lead board scroll"><div id="boardScrollInner"></div></div><div class="board" id="leadBoard">${stages.map(s=>{let arr=f.filter(l=>l.stageId===s.id);return `<div class="col" ondragover="event.preventDefault();this.classList.add('over')" ondragleave="this.classList.remove('over')" ondrop="dropLead(event,'${s.id}',this)"><div class="colhead"><span class="stage-title"><i class="dot" style="background:${s.color}"></i>${esc(s.name)}</span><span class="count">${arr.length}</span></div>${arr.map(card).join('')||'<div class="empty">No leads</div>'}</div>`}).join('')}</div>`}

function card(l){const client=l.company?.trim()||'';const clientLine=client&&client.toLowerCase()!==l.name.trim().toLowerCase()?'<div class="client-name">'+esc(client)+'</div>':'';return '<article class="leadcard '+(state.selectedIds.has(l.id)?'selected':'')+'" draggable="true" ondragstart="event.dataTransfer.setData(\'text/plain\',\''+l.id+'\')" onclick="openLead(\''+l.id+'\')"><div class="ctop"><input type="checkbox" onclick="event.stopPropagation();toggleSelect(\''+l.id+'\')" '+(state.selectedIds.has(l.id)?'checked':'')+'><div class="lead-primary"><b>'+esc(l.name)+'</b>'+clientLine+'<div class="lead-phone">'+esc(l.phone||l.email||'No contact')+'</div></div><div class="assignee avatar">'+esc(user(l.assignedUserId)?.avatar||'?')+'</div></div><div class="meta"><span>'+(l.source?esc(l.source):'')+'</span><div class="tags">'+l.tagIds.map(id=>tag(id)).filter(Boolean).map(t=>'<span class="tag" style="background:'+t.color+'22;color:'+t.color+'">'+esc(t.name)+'</span>').join('')+'<span class="muted" style="margin-left:auto">'+esc(activityTime(l))+'</span></div></article>'}
function table(f){return `<div class="tablewrap"><table><thead><tr><th><input type="checkbox" onclick="selectAll(this.checked)"></th><th>Lead</th><th>Phone</th><th>Stage</th><th>Owner</th><th>Source</th><th>Last activity</th></tr></thead><tbody>${f.map(l=>`<tr onclick="openLead('${l.id}')"><td><input type="checkbox" onclick="event.stopPropagation();toggleSelect('${l.id}')" ${state.selectedIds.has(l.id)?'checked':''}></td><td><b>${esc(l.name)}</b><small>${esc(l.company||l.name)}</small></td><td><strong class="table-phone">${esc(l.phone||l.email||'—')}</strong></td><td>${esc(stage(l.stageId)?.name)}</td><td>${esc(user(l.assignedUserId)?.name)}</td><td>${esc(l.source)}</td><td>${esc(activityTime(l))}</td></tr>`).join('')}</tbody></table></div>`}
function activityTime(l){return l.lastActivityAt?new Date(l.lastActivityAt).toLocaleDateString():''}
function drawer(id){let l=leads.find(x=>x.id===id);if(!l)return '';return `<div class="drawerbg" onclick="if(event.target===this){state.selected=null;render()}"><aside class="drawer"><div class="dhead"><div><small class="muted">Lead</small><h2>${esc(l.name)}</h2><p>${esc(l.company||l.name)}</p></div><button class="btn iconbtn" onclick="state.selected=null;render()">×</button></div><div class="dactions"><a class="btn" href="tel:${esc(l.phone)}">☎ Call</a><a class="btn" target="_blank" href="https://wa.me/${wa(l.phone)}">WhatsApp</a><button class="btn" onclick="addActivity('${l.id}')">＋ Activity</button><button class="btn dangerbtn" onclick="deleteLead('${l.id}')">Delete</button></div><div class="dbody"><div class="field"><label>Name</label><input value="${esc(l.name)}" onchange="patchLead('${l.id}',{name:this.value})"></div><div class="field"><label>Phone</label><input value="${esc(l.phone)}" onchange="patchLead('${l.id}',{phone:this.value})"></div><div class="field"><label>Email</label><input value="${esc(l.email)}" onchange="patchLead('${l.id}',{email:this.value})"></div><div class="field"><label>Company</label><input value="${esc(l.company)}" onchange="patchLead('${l.id}',{company:this.value})"></div><div class="field"><label>Source</label><input value="${esc(l.source)}" onchange="patchLead('${l.id}',{source:this.value})"></div><div class="field"><label>Stage</label><select onchange="patchLead('${l.id}',{stage_id:this.value})">${stages.map(s=>`<option value="${s.id}" ${l.stageId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Assigned user</label><select onchange="patchLead('${l.id}',{assigned_user_id:this.value})">${users.map(u=>`<option value="${u.id}" ${l.assignedUserId===u.id?'selected':''}>${esc(u.name)}</option>`).join('')}</select></div><div class="field"><label>Tags</label><div class="tags">${tags.map(t=>`<label class="tag" style="background:${t.color}22;color:${t.color};cursor:pointer"><input type="checkbox" ${l.tagIds.includes(t.id)?'checked':''} onchange="toggleLeadTag('${l.id}','${t.id}',this.checked)">${esc(t.name)}</label>`).join('')}</div></div><div class="field"><label>Notes</label><textarea onchange="patchLead('${l.id}',{notes:this.value})">${esc(l.notes)}</textarea></div><div class="field"><label>Activity timeline</label><div class="activity">${(l.activities||[]).map(a=>`<div><b>${esc(a.text)}</b><small>${esc(a.user?.name||'User')} · ${new Date(a.createdAt).toLocaleString()}</small></div>`).join('')||'<span class="muted">No activity yet.</span>'}</div></div></div></aside></div>`}
function addModal(){return `<div class="modalbg"><div class="modal"><div class="mhead"><h2>Add Lead</h2><button class="btn iconbtn" onclick="state.modal=null;render()">×</button></div><form class="form" onsubmit="addLead(event)">${field('name','Name',true)}${field('phone','Phone')}${field('email','Email','', 'email')}${field('company','Company')}${field('source','Source')}${`<label>Stage<select name="stage_id">${stages.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label>`}${`<label>Assigned user<select name="assigned_user_id">${users.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select></label>`}<label class="full">Tags<div class="tags">${tags.map(t=>`<label class="tag" style="background:${t.color}22;color:${t.color}"><input type="checkbox" name="tag_ids" value="${t.id}">${esc(t.name)}</label>`).join('')}</div></label><label class="full">Notes<textarea name="notes"></textarea></label><div class="mfoot full"><button type="button" class="btn" onclick="state.modal=null;render()">Cancel</button><button class="btn primary">Create Lead</button></div></form></div></div>`}
function field(name,label,req,type='text'){return `<label>${label}<input name="${name}" type="${type}" ${req===true?'required':''}></label>`}
function importModal(){return `<div class="modalbg"><div class="modal wide"><div class="mhead"><div><h2>Import leads</h2><p>Append or update leads. Existing leads are never deleted.</p></div><button class="btn iconbtn" onclick="state.modal=null;render()">×</button></div><div class="drop" onclick="document.getElementById('file').click()">⇧ <strong>Choose Excel, CSV or ZIP</strong><span>ZIP may contain multiple .xlsx, .xls or .csv package files. Name is optional; email or phone is enough.</span><input id="file" type="file" accept=".xlsx,.xls,.csv,.zip" multiple onchange="readFiles(event)"></div><div id="importPreview"></div><div class="import-note">Matching priority: normalized email, then normalized phone. New rows are added; matching rows are updated without deleting unrelated CRM data.</div><div class="mfoot"><button class="btn" onclick="downloadTemplate()">⇩ Template</button><button class="btn" onclick="state.modal=null;render()">Cancel</button><button id="importBtn" class="btn primary" disabled onclick="finishImport()">Import Leads</button></div></div></div>`}
let importRows=[];
function normalizeImportRow(row){
  const clean=s=>String(s??'').replace(/\u00a0/g,' ').trim();
  const key=s=>clean(s).toLowerCase().replace(/[ _-]+/g,'').replace(/[^a-z0-9]/g,'');
  const entries=Object.entries(row||{}).map(([k,v])=>({key:key(k),label:clean(k).toLowerCase(),value:clean(v)}));
  const nonEmpty=entries.filter(x=>x.value);
  const scoreMatch=(x,p)=>p instanceof RegExp&&p.test(x.key);
  const find=(patterns)=>{
    let best=null,bestScore=-1;
    for(const x of nonEmpty){
      let score=0;
      patterns.forEach((p,i)=>{if(scoreMatch(x,p)) score=Math.max(score,patterns.length-i)});
      if(score>bestScore){best=x;bestScore=score}
    }
    return best?.value||'';
  };
  const looksLikeEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean(v));
  const looksLikePhone=v=>{const s=clean(v);if(!s||s.includes('@'))return false;const digits=s.replace(/\D/g,'');return digits.length>=7&&digits.length<=16};
  const looksLikeName=v=>{const s=clean(v);if(!s||s.length<2||s.length>120||looksLikeEmail(s)||looksLikePhone(s))return false;return /\p{L}/u.test(s)&&!/^\d+$/.test(s)};
  let name=find([/^fullname$/, /^name$/, /^leadname$/, /^customername$/, /^clientname$/, /^contactname$/, /^passengername$/, /^guestname$/, /^personname$/, /^travellername$/, /^travelername$/, /givenname/, /^firstname$/, /^lastname$/, /surname/, /familyname/]);
  if(!looksLikeName(name)){
    const first=find([/^firstname$/, /^givenname$/, /^first$/]),last=find([/^lastname$/, /^surname$/, /^familyname$/, /^last$/]);
    name=[first,last].filter(Boolean).join(' ').trim();
  }
  if(!looksLikeName(name)) name=nonEmpty.find(x=>/^(full)?name$|^(lead|customer|client|contact|passenger|travell?er|guest)name$/.test(x.key)&&looksLikeName(x.value))?.value||'';
  if(!looksLikeName(name)) name=nonEmpty.find(x=>looksLikeName(x.value))?.value||'';

  let phone=find([/^phone$/, /phonenumber/, /phoneno/, /phonecontact/, /^mobile$/, /mobilenumber/, /mobileno/, /cell/, /telephone/, /telnumber/, /contactnumber/, /contactno/, /whatsapp/, /whatsappnumber/]);
  if(!looksLikePhone(phone)) phone=nonEmpty.find(x=>/(phone|mobile|cell|telephone|tel|whatsapp|contact)/.test(x.key)&&looksLikePhone(x.value))?.value||'';
  if(!looksLikePhone(phone)) phone=nonEmpty.find(x=>looksLikePhone(x.value))?.value||'';

  let email=find([/^email$/, /emailaddress/, /emailid/, /mailaddress/, /^e-mail/]);
  if(!looksLikeEmail(email)) email=nonEmpty.find(x=>looksLikeEmail(x.value))?.value||'';

  const company=find([/^company$/, /companyname/, /^business$/, /businessname/, /organization/, /organisation/, /employer/]);
  const source=find([/^source$/, /leadsource/, /campaign/, /channel/, /medium/, /marketing/]);
  const stage=find([/^stage$/, /leadstage/, /status/]);
  const assigneduser=find([/assigneduser/, /assignedto/, /ownername/, /salesperson/, /agentname/, /agent/, /owner/]);
  const agentid=find([/^agentid$/, /agentcode/, /employeeid/]);
  const tags=find([/^tags?$/, /labels?/, /categories/, /segments/]);
  const notes=find([/^notes?$/, /comments?/, /remarks/, /description/, /message/]);
  const out={...row};
  if(name)out.name=name;
  if(phone)out.phone=phone;
  if(email)out.email=email;
  if(company)out.company=company;
  if(source)out.source=source;
  if(stage)out.stage=stage;
  if(assigneduser)out.assigneduser=assigneduser;
  if(agentid)out.agentid=agentid;
  if(tags)out.tags=tags;
  if(notes)out.notes=notes;
  return out;
}
function normalizeImportRowLegacy(row){let o={};Object.entries(row).forEach(([k,v])=>o[k.toLowerCase().replace(/[ _-]/g,'')]=v);return o}
function previewImport(rows,files){importRows=rows;let valid=0,errors=0;rows.forEach(row=>{let o=normalizeImportRow(row);if(o.name||o.phone||o.email)valid++;else errors++});let html=`<div class="preview"><div class="import-note"><b>${files.length}</b> file(s) · <b>${rows.length}</b> total rows · <b>${valid}</b> ready · <b>${errors}</b> errors</div><table><thead><tr><th>#</th><th>Name</th><th>Phone</th><th>Email</th><th>Stage</th><th>Agent ID</th><th>Status</th></tr></thead><tbody>`;rows.slice(0,20).forEach((row,i)=>{let o=normalizeImportRow(row),ok=!!(o.name||o.phone||o.email);html+=`<tr><td>${i+1}</td><td>${esc(o.name||'')}</td><td>${esc(o.phone||'')}</td><td>${esc(o.email||'')}</td><td>${esc(o.stage||'New Leads')}</td><td>${esc(o.agentid||o.assigneduser||'')}</td><td class="${ok?'':'error'}">${ok?'Ready':'Missing name, phone and email'}</td></tr>`});html+='</tbody></table></div>';document.getElementById('importPreview').innerHTML=html;document.getElementById('importBtn').disabled=rows.length===0||errors===rows.length}
async function parseWorkbook(file){
  let wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),out=[];
  wb.SheetNames.forEach(sheetName=>{
    const matrix=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,defval:'',raw:false});if(!matrix.length)return;
    const pats=[/name|customer|client|contact|passenger|travell?er|guest/i,/phone|mobile|cell|telephone|tel|whatsapp/i,/email|e-mail|mail/i,/company|business|organization|employer/i,/source|campaign|channel|medium/i,/stage|status/i,/agent|owner|assigned/i,/tag|label|category/i,/note|comment|remark|description|message/i];
    let hi=0,best=-1;matrix.slice(0,15).forEach((row,i)=>{const score=row.filter(v=>pats.some(p=>p.test(String(v??'')))).length;if(score>best){best=score;hi=i}});
    const headers=(matrix[hi]||[]).map((h,i)=>String(h??'').replace(/\u00a0/g,' ').trim()||'Column '+(i+1));
    matrix.slice(hi+1).forEach(values=>{if(!values.some(v=>String(v??'').trim()))return;const row={};headers.forEach((h,i)=>row[h]=values[i]??'');out.push(row)});
  });return out;
}
async function readFiles(e){let files=[...e.target.files];let rows=[];try{for(const f of files){if(f.name.toLowerCase().endsWith('.zip')){let zip=await JSZip.loadAsync(f);for(const path of Object.keys(zip.files)){if(zip.files[path].dir||!(/\.(xlsx|xls|csv)$/i.test(path)))continue;let blob=await zip.files[path].async('blob');rows=rows.concat(await parseWorkbook(new File([blob],path.split('/').pop())))} }else{rows=rows.concat(await parseWorkbook(f))}}previewImport(rows,files)}catch(err){toast('Could not read the selected files: '+err.message)}}
async function finishImport(){try{const normalizedRows=importRows.map(normalizeImportRow);let r=await api('/leads/import',{method:'POST',body:JSON.stringify({rows:normalizedRows})});await loadData();state.modal=null;render();toast('Import complete · '+r.added+' added · '+r.updated+' updated · '+r.skipped+' skipped'+(r.errors?.length?' · '+r.errors.length+' row issue(s)':''));}catch(e){toast('Import failed: '+e.message);console.error('Lead import failed:',e)}}
function downloadTemplate(){let rows=[{Name:'Example Lead',Phone:'03001234567',Email:'example@email.com',Company:'Example Company',Source:'Meta Ads',Stage:'New Leads','Assigned User':'Ali Khan',Tags:'Hot, VIP',Notes:'Example note','Created Date':new Date().toISOString().slice(0,10)}];let ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Leads');XLSX.writeFile(wb,'leadflow-import-template.xlsx')}
function exportCSV(){let rows=visible().map(l=>({Name:l.name,Phone:l.phone,Email:l.email,Company:l.company,Source:l.source,Stage:stage(l.stageId)?.name,'Assigned User':user(l.assignedUserId)?.name,Tags:l.tagIds.map(x=>tag(x)?.name).filter(Boolean).join(', '),Notes:l.notes,'Created Date':l.createdAt}));let ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Leads');XLSX.writeFile(wb,'leadflow-leads.xlsx')}
function usersPage(){let agents=users.filter(u=>u.role!=='Administrator');return `<section class="content"><div class="pagehero"><div><div class="eyebrow">TEAM MANAGEMENT</div><h1>Agents</h1><p>View the whole team and collaborate on leads. Only the administrator can create, edit, deactivate or delete agent accounts.</p></div>${me.role==='Administrator'?'<div class="actions"><button class="btn primary" onclick="state.modal=\'agent\';render()">＋ Create Agent</button></div>':''}</div><div class="access-banner"><div class="access-icon">✓</div><div><b>Shared team workspace</b><span>All agents can see the same CRM leads, agents, stages, tags and activity history. Account management stays with the administrator.</span></div></div><div class="section-label">${agents.length} agent${agents.length===1?'':'s'} · team directory</div><div class="users-grid">${agents.map(u=>{let count=leads.filter(l=>l.assignedUserId===u.id).length;return `<article class="agent-card"><div class="agent-top"><div class="avatar xl">${esc(u.avatar)}</div><div class="agent-main"><div class="agent-name">${esc(u.name)}</div><div class="agent-id">${esc(u.agentId)}</div></div><span class="status ${u.active?'active':'inactive'}"><i></i>${u.active?'Active':'Inactive'}</span></div><div class="agent-stat"><strong>${count}</strong><span>assigned leads</span></div><div class="login-line"><span>Login email</span><b title="${esc(u.email)}">${esc(u.email)}</b></div>${me.role==='Administrator'?`<div class="agent-actions"><button class="btn" onclick="editAgent('${u.id}')">Edit account</button><button class="btn" onclick="resetAgent('${u.id}')">Reset password</button><button class="btn" onclick="toggleAgent('${u.id}',${!u.active})">${u.active?'Deactivate':'Activate'}</button><button class="btn dangerbtn" onclick="deleteAgent('${u.id}')">Delete account</button></div>`:'<div class="muted">Account changes are administrator-only.</div>'}</article>`}).join('')||'<div class="empty-state"><b>No agents yet</b></div>'}</div></section>`}
function agentModal(){return `<div class="modalbg"><div class="modal compact"><div class="mhead"><div><div class="eyebrow">NEW ACCOUNT</div><h2>Create Agent</h2><p>Give the agent their own secure login.</p></div><button class="btn iconbtn" onclick="state.modal=null;render()">×</button></div><form class="form" onsubmit="createAgent(event)"><label class="full">Full name<input name="name" required placeholder="e.g. Ahmed Khan"></label><label class="full">Login email<input name="email" type="email" required placeholder="agent@company.com"></label><label class="full">Password<input name="password" type="password" minlength="8" required placeholder="Minimum 8 characters"></label><div class="security-note full"><b>Shared team workspace</b><span>This agent can work with all CRM leads. Lead assignment is a shared team workflow.</span></div><div class="mfoot full"><button type="button" class="btn" onclick="state.modal=null;render()">Cancel</button><button type="submit" class="btn primary">Create Agent</button></div></form></div></div>`}
function editAgentModal(u){return `<div class="modalbg"><div class="modal compact"><div class="mhead"><div><div class="eyebrow">ACCOUNT SETTINGS · ${esc(u.agentId)}</div><h2>Edit Agent</h2><p>Update login email or set a new password.</p></div><button class="btn iconbtn" onclick="state.modal=null;render()">×</button></div><form class="form" onsubmit="saveAgent(event,'${u.id}')"><label class="full">Agent name<div class="readonly">${esc(u.name)}</div></label><label class="full">Login email<input name="email" type="email" value="${esc(u.email)}" required></label><label class="full">New password<input name="password" type="password" minlength="8" placeholder="Leave blank to keep current password"></label><div class="security-note full"><b>Password is securely hashed</b><span>The CRM never stores the agent's password as plain text.</span></div><div class="mfoot full"><button type="button" class="btn" onclick="state.modal=null;render()">Cancel</button><button type="submit" class="btn primary">Save changes</button></div></form></div></div>`}
async function createAgent(e){e.preventDefault();const form=e?.currentTarget||e?.target;if(!form||form.tagName!=='FORM'){toast('Agent form could not be read. Please refresh the page.');return}try{const p={name:form.elements.name?.value?.trim()||'',email:form.elements.email?.value?.trim()||'',password:form.elements.password?.value||''};if(!p.name||!p.email||p.password.length<8){toast('Enter a name, valid email, and password of at least 8 characters.');return}const r=await api('/users',{method:'POST',body:JSON.stringify(p)});await loadData();state.modal=null;render();toast(`Agent created · ${r.credentials.agentId}`);setTimeout(()=>alert(`Agent created successfully\n\nAgent ID: ${r.credentials.agentId}\nLogin email: ${r.credentials.email}\nPassword: ${r.credentials.password}`),80)}catch(err){toast(err.message)}}
function editAgent(id){let u=user(id);if(u){state.modal='editAgent';state.editUser=id;render()}}
async function saveAgent(e,id){e.preventDefault();const form=e?.currentTarget||e?.target;if(!form||form.tagName!=='FORM'){toast('Agent form could not be read.');return}try{let email=form.elements.email?.value?.trim()||'',password=form.elements.password?.value||'';if(!email){toast('Email is required.');return}if(password&&password.length<8){toast('Password must be at least 8 characters.');return}let body={email};if(password)body.password=password;await api('/users/'+id,{method:'PATCH',body:JSON.stringify(body)});await loadData();state.modal=null;state.editUser=null;render();toast('Agent account updated')}catch(e){toast(e.message)}}
async function deleteAgent(id){let u=user(id);if(!u||!confirm('Delete '+u.name+' account? Any assigned leads will move to the administrator.'))return;try{await api('/users/'+id,{method:'DELETE'});await loadData();render();toast('Agent account deleted')}catch(e){toast(e.message)}}
async function toggleAgent(id,active){try{await api('/users/'+id+'/active?active='+active,{method:'PATCH'});await loadData();render();toast(active?'Agent activated':'Agent deactivated')}catch(e){toast(e.message)}}
async function resetAgent(id){let u=user(id);if(!u)return;let pw=prompt(`New password for ${u.name} (minimum 8 characters)`);if(!pw)return;if(pw.length<8)return toast('Password must be at least 8 characters');try{let r=await api('/users/'+id+'/reset-password?password='+encodeURIComponent(pw),{method:'POST'});alert(`Password reset\n\nAgent ID: ${r.credentials.agentId}\nLogin email: ${r.credentials.email}\nNew password: ${r.credentials.password}`);toast('Password reset successfully')}catch(e){toast(e.message)}}
function settingsPage(){return `<section class="content"><div class="head"><div><h1>Settings</h1><p>Customize pipeline stages and tags. Changes are stored in the backend database.</p></div></div><div class="settings-grid"><div class="kpi"><b>Pipeline stages</b><p class="muted">Rename, recolor, reorder and remove stages.</p>${stages.map((s,i)=>`<div class="row"><span class="dot" style="width:9px;height:9px;border-radius:50%;background:${s.color}"></span><input class="select" value="${esc(s.name)}" onchange="editStage('${s.id}',this.value,'${s.color}')"><input type="color" value="${s.color}" style="width:38px;height:35px;padding:3px" onchange="editStage('${s.id}','${esc(s.name)}',this.value)"><button class="btn" onclick="moveStage('${s.id}',-1)">↑</button><button class="btn" onclick="moveStage('${s.id}',1)">↓</button><button class="btn" onclick="removeStage('${s.id}')">×</button></div>`).join('')}<button class="btn primary" style="margin-top:12px" onclick="addStage()">＋ Add stage</button></div><div class="kpi"><b>Tags</b><p class="muted">Custom labels for prioritization and workflows.</p>${tags.map(t=>`<div class="row"><input class="select" value="${esc(t.name)}" onchange="editTag('${t.id}',this.value,'${t.color}')"><input type="color" value="${t.color}" style="width:38px;height:35px;padding:3px" onchange="editTag('${t.id}','${esc(t.name)}',this.value)"><button class="btn" onclick="removeTag('${t.id}')">×</button></div>`).join('')}<button class="btn primary" style="margin-top:12px" onclick="addTag()">＋ Add tag</button></div></div></section>`}
async function loadData(){let d=await api('/bootstrap');users=d.users;stages=d.stages;tags=d.tags;leads=d.leads;notifications=await api('/notifications')}
async function patchLead(id,p){try{let payload={};Object.entries(p).forEach(([k,v])=>payload[k==='stage_id'?'stage_id':k==='assigned_user_id'?'assigned_user_id':k]=v);let l=await api('/leads/'+id,{method:'PATCH',body:JSON.stringify(payload)});let i=leads.findIndex(x=>x.id===id);leads[i]=l;render();toast('Lead updated')}catch(e){toast(e.message)}}
async function addLead(e){e.preventDefault();const form=e?.currentTarget||e?.target;if(!form||form.tagName!=='FORM'){toast('Lead form could not be read. Please refresh the page.');return}try{const fd=new FormData(form),tag_ids=fd.getAll('tag_ids');const p=Object.fromEntries(fd.entries());p.tag_ids=tag_ids;const l=await api('/leads',{method:'POST',body:JSON.stringify(p)});leads.unshift(l);state.modal=null;render();toast('Lead created')}catch(err){toast(err.message)}}
async function addActivity(id){let t=prompt('Activity note');if(!t)return;try{let a=await api('/leads/'+id+'/activities',{method:'POST',body:JSON.stringify({text:t})});let l=leads.find(x=>x.id===id);l.activities.unshift(a);l.lastActivityAt=a.createdAt;render();toast('Activity added')}catch(e){toast(e.message)}}
async function toggleLeadTag(id,tid,on){let l=leads.find(x=>x.id===id),ids=[...l.tagIds];on?ids.push(tid):ids=ids.filter(x=>x!==tid);await patchLead(id,{tag_ids:[...new Set(ids)]})}
async function move(id,s){await patchLead(id,{stage_id:s})}function dropLead(e,s,el){el.classList.remove('over');move(e.dataTransfer.getData('text/plain'),s)}
function openLead(id){state.selected=id;render()}function go(p){state.page=p;state.selected=null;state.selectedIds.clear();render()}function toggleSelect(id){state.selectedIds.has(id)?state.selectedIds.delete(id):state.selectedIds.add(id);render()}function selectAll(v){visible().forEach(l=>v?state.selectedIds.add(l.id):state.selectedIds.delete(l.id));render()}
async function bulkStage(s){if(!s)return;try{await Promise.all([...state.selectedIds].map(id=>api('/leads/'+id,{method:'PATCH',body:JSON.stringify({stage_id:s})})));await loadData();state.selectedIds.clear();render();toast('Stage updated')}catch(e){toast(e.message)}}
async function bulkAssign(u){if(!u)return;try{await Promise.all([...state.selectedIds].map(id=>api('/leads/'+id,{method:'PATCH',body:JSON.stringify({assigned_user_id:u})})));await loadData();state.selectedIds.clear();render();toast('Assignment updated')}catch(e){toast(e.message)}}
async function bulkTag(){let n=prompt('Enter existing tag name');let t=tags.find(x=>x.name.toLowerCase()===String(n||'').toLowerCase());if(!t)return toast('Tag not found');try{await Promise.all([...state.selectedIds].map(async id=>{let l=leads.find(x=>x.id===id);return api('/leads/'+id,{method:'PATCH',body:JSON.stringify({tag_ids:[...new Set([...l.tagIds,t.id])]})})}));await loadData();state.selectedIds.clear();render();toast('Tag added')}catch(e){toast(e.message)}}
async function deleteLead(id){if(!confirm('Delete this lead?'))return;try{await api('/leads/'+id,{method:'DELETE'});leads=leads.filter(x=>x.id!==id);state.selected=null;render();toast('Lead deleted')}catch(e){toast(e.message)}}
async function editStage(id,name,color){try{let s=stage(id);await api('/stages/'+id,{method:'PATCH',body:JSON.stringify({name,color})});Object.assign(s,{name,color});render()}catch(e){toast(e.message)}}
async function moveStage(id,dir){let arr=[...stages],i=arr.findIndex(x=>x.id===id),j=i+dir;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];try{await api('/stages/reorder',{method:'POST',body:JSON.stringify({ids:arr.map(x=>x.id)})});stages=arr;render()}catch(e){toast(e.message)}}
async function addStage(){let n=prompt('Stage name');if(!n)return;try{let s=await api('/stages',{method:'POST',body:JSON.stringify({name:n,color:'#64748b'})});stages.push(s);render()}catch(e){toast(e.message)}}
async function removeStage(id){if(!confirm('Remove this stage? Leads will move to the first remaining stage.'))return;try{await api('/stages/'+id,{method:'DELETE'});await loadData();render()}catch(e){toast(e.message)}}
async function editTag(id,name,color){try{await api('/tags/'+id,{method:'PATCH',body:JSON.stringify({name,color})});let t=tag(id);Object.assign(t,{name,color});render()}catch(e){toast(e.message)}}
async function addTag(){let n=prompt('Tag name');if(!n)return;try{let t=await api('/tags',{method:'POST',body:JSON.stringify({name:n,color:'#64748b'})});tags.push(t);render()}catch(e){toast(e.message)}}
async function removeTag(id){if(!confirm('Delete this tag?'))return;try{await api('/tags/'+id,{method:'DELETE'});await loadData();render()}catch(e){toast(e.message)}}
function wa(phone){let n=String(phone||'').replace(/\D/g,'');if(n.startsWith('0'))n='92'+n.slice(1);if(!n.startsWith('92'))n='92'+n;return n}
function showNotifications(){if(!notifications.length){toast('No notifications');return}let unread=notifications.filter(n=>!n.read);alert(notifications.slice(0,8).map(n=>(n.read?'• ':'🔔 ')+n.text+' · '+new Date(n.createdAt).toLocaleString()).join('\n'));if(unread.length){api('/notifications/read',{method:'POST',body:JSON.stringify({ids:unread.map(n=>n.id)})}).then(()=>{notifications.forEach(n=>n.read=true);render()}).catch(()=>{})}}
function logout(){token='';localStorage.removeItem('leadflow_token');me=null;leads=[];notifications=[];render()}
async function boot(){
  render();
  if(!token)return;
  try{me=await api('/me');await loadData();render()}
  catch(e){token='';localStorage.removeItem('leadflow_token');me=null;render();toast(e.message||'Could not connect to the CRM server')}
}boot();
